### ISSUE TITLE
Fail on requiring optional field in json response for `user info`

### ISSUE THREAD

**Issue by boozook** [Hirevo/mega-cli-rs#2]
The field `country` in the account info is __optional__.

Also I has no filled non-optional field "last name", so it can be empty too.

<details><summary>screenshot</summary>

<img width="654" alt="Screenshot 2024-09-20 at 01 37 16" src="https://github.com/user-attachments/assets/e77bba59-443f-4dc2-a947-73b1e29ace2e">

</details>

```
mega auth me                                                                  
ERROR: `mega-cli` terminated due to an error.

  × could not fetch current user info
  ├─▶ JSON error: missing field `country`
  ╰─▶ missing field `country`
```

**Comment by Hirevo** [comment]
Hello, thanks for reporting this issue.

I've released what should be a fix in the v0.7.4 release of the `mega-rs` library.
You should be able to make use of this fix within `mega-cli-rs` by simply rebuilding the binary, if you had it installed via Cargo, using the following command:
```bash
cargo install mega-cli
```

Feel free to report whether this succeeds in fixing your issue or not.
If not, I'll re-open this issue, look into it again and also consider making a dedicated `mega-cli-rs` release.
